[general]
use_julia_native_enum_type = true
print_using_CEnum = false
library_name = "libmkl_rt"
output_file_path = "../src/libmklsparse.jl"

[codegen]
use_julia_bool = true
use_ccall_macro = true
always_NUL_terminated_string = false
