module MKLSparse

using LinearAlgebra, SparseArrays
using LinearAlgebra: BlasInt, BlasFloat, checksquare
using MKL_jll: libmkl_rt

# For testing purposes:
global const __counter = Ref(0)

function __init__()
    @ccall libmkl_rt.MKL_Set_Interface_Layer((Base.USE_BLAS64 ? 1 : 0)::Cint)::Cint
end

# Wrappers generated by Clang.jl
include("libmklsparse.jl")
include("types.jl")

# TODO: BLAS1

# BLAS2 and BLAS3
include("matdescra.jl")
include("generator.jl")
include("matmul.jl")

end # module
