module MKLSparse

using LinearAlgebra, SparseArrays
using LinearAlgebra: BlasInt, BlasFloat, checksquare
using MKL_jll

p = MKL_jll.libmkl_rt
libmkl_rt = joinpath((splitpath(p)[1:end-1])..., "libmkl_intel_ilp64")

# For testing purposes:
global const __counter = Ref(0)

# Wrappers generated by Clang.jl
include("libmklsparse.jl")
include("types.jl")

# TODO: BLAS1

# BLAS2 and BLAS3
include("matdescra.jl")
include("generator.jl")
include("matmul.jl")

end # module
